// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package each

type StringStringMap map[string]string

func (m StringStringMap) Each(aply func(key string, value string) bool) {
	for k, v := range m {
		if !aply(k, v) {
			break
		}
	}
}

type StringIntMap map[string]int

func (m StringIntMap) Each(aply func(key string, value int) bool) {
	for k, v := range m {
		if !aply(k, v) {
			break
		}
	}
}

type StringBoolMap map[string]bool

func (m StringBoolMap) Each(aply func(key string, value bool) bool) {
	for k, v := range m {
		if !aply(k, v) {
			break
		}
	}
}
