// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package fold

func FoldFloat64(l []float64, apply func(a float64, b float64) float64) (res float64) {
	res = l[0]
	for _, v := range l[1:] {
		res = apply(res, v)
	}
	return res
}

func FoldInt(l []int, apply func(a int, b int) int) (res int) {
	res = l[0]
	for _, v := range l[1:] {
		res = apply(res, v)
	}
	return res
}
